# Generated by Django 4.0.1 on 2022-01-23 22:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('quantity', models.IntegerField(default=1)),
                ('is_returnable', models.BooleanField()),
                ('description', models.TextField(max_length=480)),
                ('category', models.CharField(choices=[('EL', 'Electronics'), ('CO', 'Collectibles & Art'), ('FA', 'Fashion'), ('MO', 'Motors'), ('TO', 'Toys & Hobbies'), ('SP', 'Sports'), ('HE', 'Health & Beauty'), ('BO', 'Books, Movies & Music'), ('BU', 'Business & Industrial'), ('HO', 'Home & Garden'), ('OT', 'Other')], max_length=24)),
                ('list_price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('buynow_price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('ship_price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('listing_start', models.DateTimeField(auto_now_add=True)),
                ('listing_end', models.DateTimeField()),
                ('listing_timeout', models.DateTimeField()),
                ('lister', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=280)),
                ('is_hidden', models.BooleanField()),
                ('commented', models.DateTimeField(auto_now_add=True)),
                ('commenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctions.listing')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_comment', to='auctions.comment')),
            ],
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid_price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('bid_time', models.DateTimeField(auto_now_add=True)),
                ('bidder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctions.listing')),
            ],
        ),
    ]
