# Generated by Django 4.0.1 on 2022-01-25 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_listing_comment_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='listing',
            name='buynow_price',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=9),
        ),
        migrations.AlterField(
            model_name='listing',
            name='listing_end',
            field=models.DateTimeField(default=None),
        ),
    ]
