# Generated by Django 4.0.1 on 2022-01-30 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_alter_comment_is_hidden_alter_listing_buynow_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='is_hidden',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='buynow_price',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='is_returnable',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='listing_end',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='listing_start',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='listing_timeout',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='ship_price',
        ),
        migrations.AddField(
            model_name='listing',
            name='image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='is_active',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bid',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auction', to='auctions.listing'),
        ),
    ]
