# Generated by Django 4.0.1 on 2022-02-05 21:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_remove_comment_is_hidden_remove_listing_buynow_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='parent',
        ),
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('BO', 'Books, Movies & Music'), ('BU', 'Business & Industrial'), ('CO', 'Collectibles & Art'), ('EL', 'Electronics'), ('FA', 'Fashion'), ('HE', 'Health & Beauty'), ('HO', 'Home & Garden'), ('MO', 'Motors'), ('SP', 'Sports'), ('TO', 'Toys & Hobbies'), ('OT', 'Other')], max_length=24),
        ),
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctions.listing')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
