# Generated by Django 4.0.3 on 2022-04-03 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_rename_timestamp_post_posted_post_edited'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, max_length=280),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_pic_url',
            field=models.URLField(blank=True),
        ),
    ]
